modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="islandsmod"
version="1.0.0"
displayName="Flying Islands Generation"
description='''Replaces overworld generation with flying islands of various sizes over the void.'''

[[dependencies.islandsmod]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.islandsmod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.islandsmod]]
    modId="jei"
    type="optional"
    versionRange="[19.21.1,)"
    ordering="NONE"
    side="CLIENT"
